theme: jekyll-theme-hacker

title: About me Tales Casagrande a.ka. Taleco
description: [A guy with passion for cyber security!]
description: [Here you find my social links, blog posts, pics and random thinks]

